# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/srozhkov/develop/csqemu
TARGET_DIRS=riscv64-lib-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/home/srozhkov/develop/csqemu/build-lib/pyvenv/bin/python3 -B
GENISOIMAGE=
MESON=/home/srozhkov/develop/csqemu/build-lib/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS=
