#
#  Demo 1
#

name: demo-workflow

on: [workflow_dispatch]
 
jobs:
  Run-trivial-demo:
    runs-on: ubuntu-latest
    container:
      image: slyubski/bldq:1.0.1
    steps:
      - run: echo "The very first GUTHUB demo ......."
      - run: pwd
      - run: ls -la /
      - run: which pkg-config
      - run: which gcc
      - run: which ninja
      - name: --- Check out git repo ------
        uses: actions/checkout@v4
      - run: ls -la
      - run: ./build-fake.sh INSTALL  5567
      - run: ls -la INSTALL
      - run: echo " ==== ${{ github.job }} ==== "
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: qemu-build
          path: |
            INSTALL
            INSTALL/*.tar
