#
#  Demo 1
#

name: demo-workflow

on: [workflow_dispatch]
 
jobs:
  Run-trivial-demo:
    runs-on: ubuntu-latest
    container:
      image: slyubski/bldq:1.0.1
    steps:
      - run: echo "The very first GUTHUB demo ......."
      - run: ls -la 
      - name: --- Check out git repo ------
        uses: actions/checkout@v4
      - run: ls -la
      - name: --- Run fake script ----
      - run: ./build-fake.sh INSTALL  5567
      - name: ---- show result ----
      - run: ls -la INSTALL
