#
#  Demo 1
#

name: demo-workflow

on: [workflow_dispatch]
 
jobs:
  Run-trivial-demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "There very first GUTHUB demo ......."
      - run: ls -la 
